### ISSUE TITLE
Provide abstraction interface to save/load arbitrary files as an Item

### ISSUE THREAD

**Issue by ribose-jeffreylau** [paneron/ruby-paneron_registry#8]
Possibly as an encoded `data:` field.

The encoding probably depends on the file type.

Encoding should also be recorded alongside the payload.

Something like:

```yaml
id: "... item id..."
data:
  type: file
  encoding: "..."  # none | base32 | base64 | ...
  payload: |
    ...
status: valid
dateAccepted: ...
```
